[package]
name = "nft-metadata-crawler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
csv = "1.2.2"
diesel = { version = "2.1.0", features = ["postgres", "chrono"] }
futures = "0.3.28"
image = "0.24.5"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.0"
tokio = { version = "1.28.2", features = ["full"] }
